[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[redirects]]
  from = "https://demonimo.netlify.app"
  to = "https://demonimo.pt"
  status = 301
  force = true